version: '2'
services:
    nginx:
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql:db
        volumes:
            - ./www:/var/www
    shipment_doc_nginx:
        container_name: shipment_doc_service
        image: nginx:latest
        ports:
            - "8081:80"
            - "8443:443"
        volumes:
            - ./shipment_docs/hosts:/etc/nginx/conf.d
            - ./shipment_docs/www:/var/www
            - ./shipment_docs/logs:/var/log/nginx
        links:
            - shipment_docs_php
    shipment_docs_php:
        build: ./shipment_docs/images/php
        links:
            - mysql:db
        volumes:
            - ./shipment_docs/www:/var/www
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysqlconf:/etc/mysql/conf.d
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - mysql